### PR TITLE
Pull in minimo upstream to v2.10.1; update devDependencies to get a working build

### PR DESCRIPTION
**Pull request by arubis**
* Merge in upstream MunifTangim/minimo at v2.10.1
* Bring Webpack to v5
* Update devDependencies bluntly until `npm run build` doesn't fail
* Move location of alert-triangle SVG to correspond with the new search path

### CODE REVIEW

**Comment by arubis** [comment]
While this won't last forever (all things JS churn fast), currently this gets a green run from both `npm audit` and via [Snyk](https://snyk.io/):
```
❯ snyk test https://github.com/arubis/engimo --dev

Testing https://github.com/arubis/engimo...

Organization:      arubis
Package manager:   npm
Open source:       yes
Project path:      https://github.com/arubis/engimo

✔ Tested https://github.com/arubis/engimo for known vulnerabilities, no vulnerable paths found.
```

**Comment by achary** [comment]
Many thanks a lot for this refreshing contribution.
It's been a while and the project has collected a lots of dust. I'm very happy for this PR and I'm very keen to bring this in.

There is one minor issue I've spotted. Trying this out with `hugo server --source=exampleSite/ --themesDir=../..` (on both latest v0.104 as well as older v0.68) gives the following error:

```bash
Error: add site dependencies: load resources: loading templates: "/home/adam/workspaces/engimo/layouts/partials/footer/scripts.html:3:1": parse failed: template: partials/footer/scripts.html:3: unexpected "#" in command
```
(the `/home/adam/workspaces/engimo` is the repo clone location on my machine)

I think the [commented out (?) line ](https://github.com/arubis/engimo/blame/master/layouts/partials/footer/scripts.html#L3) is a trouble maker here and probably it's best to just remove it completely. 

Other things LGTM.

**Comment by arubis** [comment]
Thanks, @achary -- and sorry for dropping a PR and then disappearing like that!
~I'm having trouble reproducing owing to some environment issues on my end, but removed the offending line in this branch.~ Reproduced your issue locally; removing the line you identified fixes it for me as well. I've pushed the corresponding change here.

**Comment by achary** [comment]
No worries @arubis , thanks for the extra fix -  I've checked and I haven't noticed any issues now.

**Pull request merged**
